name: bear-ne-practical
channels:
  - conda-forge
  - bioconda
dependencies:
  - bcftools
  - cxx-compiler
  - git
  - make
  - msmc2
  - plink=1.90
  - python=3.11
  - r-base
  - tabix
  # msmc-tools, GONE, GONE2, and NeEstimator are installed as described
  # in software/README.md.
