name: bear-load-practical
channels:
  - conda-forge
  - bioconda
dependencies:
  - bcftools
  - bedtools
  - cxx-compiler
  - git
  - openjdk
  - minimap2
  - samtools
  - transanno
  - ucsc-bigwigtobedgraph
  - ucsc-liftover
  - python=3.11
  - wget
  - unzip
